In [11]:
import networkx as nx
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from scipy.stats import expon
from networkx.algorithms import bipartite
#from ut import k_edge_augmentation

Необходимо было показать, что граф двудольный тогда и только тогда, когда спектр Лапласса равен "беззнаковому" спектру Лапласса. Я брал двудольные графы из сайта http://konect.uni-koblenz.de/networks/.

In [74]:
x = pd.read_csv('out.opsahl-ucforum',sep = ' ',index_col=None)
x= x.iloc[1:,:2].reset_index()
x.columns = ['node1','node2','w']
x.loc[:,'node2'] = x.node2.values + x.node1.unique().shape[0]# Прибавил число вершин в "первой доле",
x.loc[:,'node1'] = x.node1.astype(int)                          #чтобы граф был двудольным.
x.to_csv('n',header=None,sep=' ',index=None)
G = nx.read_edgelist('n',nodetype=int, data=(('weight',float),))

In [75]:
x

       node1  node2  w
0          1    900  1
1          2    900  1
2          3    901  1
3          4    900  1
4          5    900  1
5          6    902  1
6          7    900  1
7          8    900  1
8          9    900  1
9          2    903  1
10         9    903  1
11         1    903  1
12         5    903  1
13        10    900  1
14        11    904  1
15        12    900  1
16        12    903  1
17        13    905  1
18        14    905  1
19        14    905  1
20        14    905  1
21        15    905  1
22        14    905  1
23        14    905  1
24        14    905  1
25        16    906  1
26         2    906  1
27         1    906  1
28        15    906  1
29         9    906  1
...      ...    ... ..
33690    624    926  1
33691    624   1355  1
33692    624    942  1
33693    435    931  1
33694     24    942  1
33695    565    908  1
33696    565    962  1
33697    170    916  1
33698    170   1291  1
33699    170    983  1
33700    170    988  1
33701    348   1211  1
33702    348   1406  1
33703    153    954  1
33704    111   1341  1
33705    866    942  1
33706    128   1276  1
33707    213   1341  1
33708    213    962  1
33709    213    962  1
33710    572   1355  1
33711    572    926  1
33712    111   1341  1
33713    207    942  1
33714    802    926  1
33715    597    916  1
33716    597    983  1
33717    395    942  1
33718    354   1128  1
33719    354   1128  1

[33720 rows x 3 columns]

Найдем матрицу сопряженности и диагональную матрицу степеней

In [43]:
sh1 = x.shape[0]
sh2 = x.node2.values.max()
A = np.zeros((sh2,sh2))
D = np.zeros((sh2,sh2))
for i in range(sh1):
    A[x.node1.values[i]-1,x.node2.values[i]-1]=1
for k in x.node1.unique():
    D[k-1,k-1] = x[x.node1==k].shape[0]
for k in x.node2.unique():
    D[k-1,k-1] = x[x.node2==k].shape[0]

In [47]:
L1 = D - A
L2 = D + A

In [59]:
np.sum(L1.diagonal()==L2.diagonal())/L1.diagonal().shape[0]

1.0

In [96]:
x = pd.read_csv('out.brunson_club-membership_club-membership',sep = ' ',index_col=None)
x= x.iloc[1:,:2].reset_index()
x.columns = ['node1','node2','w']
x.loc[:,'node2'] = x.node2.values + x.node1.unique().shape[0]# Прибавил число вершин в "первой доле",
x.loc[:,'node1'] = x.node1.astype(int)                          #чтобы граф был двудольным.
x.to_csv('n',header=None,sep=' ',index=None)
G = nx.read_edgelist('n',nodetype=int, data=(('weight',float),))

In [99]:
x

    node1  node2   w
0       1     26 NaN
1       1     27 NaN
2       1     28 NaN
3       2     26 NaN
4       2     29 NaN
5       3     30 NaN
6       3     26 NaN
7       3     31 NaN
8       4     26 NaN
9       4     32 NaN
10      4     33 NaN
11      5     30 NaN
12      5     26 NaN
13      5     33 NaN
14      6     26 NaN
15      6     34 NaN
16      6     35 NaN
17      6     36 NaN
18      7     34 NaN
19      7     28 NaN
20      7     35 NaN
21      8     37 NaN
22      8     34 NaN
23      8     38 NaN
24      8     35 NaN
25      9     26 NaN
26      9     39 NaN
27     10     30 NaN
28     10     26 NaN
29     10     39 NaN
..    ...    ...  ..
65     18     26 NaN
66     18     34 NaN
67     18     28 NaN
68     18     39 NaN
69     19     30 NaN
70     19     26 NaN
71     19     34 NaN
72     19     36 NaN
73     19     31 NaN
74     20     26 NaN
75     20     34 NaN
76     20     38 NaN
77     21     26 NaN
78     21     38 NaN
79     21     31 NaN
80     22     30 NaN
81     22     26 NaN
82     22     40 NaN
83     22     31 NaN
84     23     37 NaN
85     23     26 NaN
86     23     34 NaN
87     23     40 NaN
88     23     31 NaN
89     24     30 NaN
90     24     26 NaN
91     24     32 NaN
92     25     30 NaN
93     25     26 NaN
94     25     29 NaN

[95 rows x 3 columns]

In [100]:
sh1 = x.shape[0]
sh2 = x.node2.values.max()
A = np.zeros((sh2,sh2))
D = np.zeros((sh2,sh2))
for i in range(sh1):
    A[x.node1.values[i]-1,x.node2.values[i]-1]=1
for k in x.node1.unique():
    D[k-1,k-1] = x[x.node1==k].shape[0]
for k in x.node2.unique():
    D[k-1,k-1] = x[x.node2==k].shape[0]

In [101]:
L1 = D - A
L2 = D + A

In [102]:
np.sum(L1.diagonal()==L2.diagonal())/L1.diagonal().shape[0]

1.0

Т. е. все элементы спектра совпали